Prueba cfl
jose-tandil-argentina/pruebaCFL pull request #4
Opened 2020-08-07 16:59 UTC by jose-tandil-argentina

chicos le dejo ahi va queriendo la practica!!!

2020-08-08 15:42 UTC, mauri52 requested changes

2020-08-08 15:42 UTC, mauri52 commented on ResgistroAutomotor.ts
> +
Tenes una mezcla interesante de conceptos...
Las dos clases hijas son identicas, no tiene sentido usar herencia si las hijas van a ser identicas. 
Ademas la clase Automotores tiene atributos que no corresponden.
Un camion y una moto tienen atibutos diferentes, por ejemplo la cantidad de ruedas, o el tipo de combustible. Eso es lo que tienen que tener las clases hijas.
Los atributos que le pusiste a ambas clases claramente tienen que ir en la clase padre, puesto que son comunes a las dos clases hijas.
Lee con mucha atencion esto y modifica el codigo.

2020-08-08 16:50 UTC, rbeltracchi requested changes

2020-08-08 16:50 UTC, rbeltracchi commented on ResgistroAutomotor.ts
> +    private camiones: string;
Si motos y camiones extienden de Automotores, por que tiene un atributo con el mismo nombre?

2020-08-08 16:50 UTC, rbeltracchi commented on ResgistroAutomotor.ts
> +    private modelos = String;
Puede tener muchos modelos y marcas un mismo camion?

2020-08-08 16:50 UTC, rbeltracchi commented on ResgistroAutomotor.ts
> +class Camiones extends Automotores{
Los nombres de las clases van en singular

2020-08-08 16:50 UTC, rbeltracchi commented on ResgistroAutomotor.ts
> +    public constructor(camiones: string, motos: string) {
Para que usas los parametros camiones y motos?

2020-08-08 16:50 UTC, rbeltracchi commented on ResgistroAutomotor.ts
> +    public Modelo(modelos: String): void{
los nombres de los metodos empiezan con minuscula. Y acordate que por lo general son verbos

2020-08-10 13:26 UTC, rbeltracchi requested changes
Jose, Como dijo Mauri tenes mezclados varios conceptos. Revisa los comentarios que hicimos entre los dos para poder empezar a corregirlos.

Acordate que es un branch por clase. Siempre estas trabajando sobre un branch pruebaCFL asi que nunca sabemos que estamos mirando

2020-08-10 13:26 UTC, rbeltracchi commented on ResgistroAutomotor.ts
>          this.longitud = longitud;
Longitud de que? para que es este metodo y variable?

2020-08-10 13:29 UTC, rbeltracchi reviewed
Otra cosa Jose, tratá de hacer los ejercicios por tu cuenta, no hagas copiar y pegar de los ejercicios de tus compañeros/as. Acordate que miramos todos los ejercicios de todos. De que te sirve copiarlos? Por mas que no te salgan tenes que intentarlos por tu cuenta.

2021-07-13 23:07 UTC, closed without merging