TELEFONO
jose-tandil-argentina/pruebaCFL pull request #5
Opened 2020-08-11 14:02 UTC by jose-tandil-argentina

chicos necesito ayuda en los metodos!!!

2020-08-11 17:25 UTC, rbeltracchi requested changes

2020-08-11 17:25 UTC, rbeltracchi commented on Telefono.ts
> +       return this.bateriaActual=100;
Siempre devuelve 100? Tenes que devolver el valor del atributo nomas, sin hacer asignaciones

2020-08-11 17:25 UTC, rbeltracchi commented on Telefono.ts
> +       return false;
Siempre devuelve que esta apagado, cuando no es asi. Tenes que devolver el valor del atributo estaPrendido

2020-08-11 17:25 UTC, rbeltracchi commented on Telefono.ts
> +       return true;
Por que devuelve un bool este metodo? Que tiene que hacer?

2020-08-11 21:52 UTC, mauri52 requested changes
Hola, le tenes que poner algo dentro de los metodos. Asi como esta no hace practicamente nada.

2020-08-12 18:09 UTC, rbeltracchi requested changes

2020-08-12 18:09 UTC, rbeltracchi commented on Telefono.ts
> +   public getPrenderApagarLinterna(): void{
Un get que no devuelve nada?

2020-08-12 19:46 UTC, rbeltracchi requested changes

2020-08-12 19:46 UTC, rbeltracchi commented on Camara.ts
> +    public savarFoto(): string{
falta el constructor

2020-08-12 19:46 UTC, rbeltracchi commented on Telefono.ts
>      private camara: Camara;
Camara de donde viene? Tendrias que importar esa clase tambien

2020-08-13 14:10 UTC, jose-tandil-argentina commented
Cámara viene de TelefonoConCamara


Enviado desde Correo<https://go.microsoft.com/fwlink/?LinkId=550986> para Windows 10

De: Rodrigo Beltracchi<mailto:notifications@github.com>
Enviado: miércoles, 12 de agosto de 2020 16:46
Para: jose-tandil-argentina/pruebaCFL<mailto:pruebaCFL@noreply.github.com>
CC: jose-tandil-argentina<mailto:josempereztandil@hotmail.com>; Author<mailto:author@noreply.github.com>
Asunto: Re: [jose-tandil-argentina/pruebaCFL] TELEFONO (#5)


@rbeltracchi requested changes on this pull request.


In Camara.ts<https://github.com/jose-tandil-argentina/pruebaCFL/pull/5#discussion_r469498864>:

> @@ -0,0 +1,6 @@

+

+class Camara {

+    public savarFoto(): string{

falta el constructor


In Telefono.ts<https://github.com/jose-tandil-argentina/pruebaCFL/pull/5#discussion_r469499229>:

> -

-

-   public getBateriiaActual(): number{

-       return this.bateriaActual;

-   }

-

-

-}

-

-

-class Camara {

-    public savarFoto(): string{

-        return "la foto del dia";

-    }

-}

+import {Telefono} from "./Telefono1";



 class TelefonoConCamara extends Telefono{

     private camara: Camara;

Camara de donde viene? Tendrias que importar esa clase tambien

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://github.com/jose-tandil-argentina/pruebaCFL/pull/5#pullrequestreview-466220629>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AQDGBEDLJ7COU77OV5XEXMTSALWSHANCNFSM4P3CHGNQ>.

2020-08-13 14:10 UTC, jose-tandil-argentina commented
Pero estaba probando lo de exportar las clases


Enviado desde Correo<https://go.microsoft.com/fwlink/?LinkId=550986> para Windows 10

De: Rodrigo Beltracchi<mailto:notifications@github.com>
Enviado: miércoles, 12 de agosto de 2020 16:46
Para: jose-tandil-argentina/pruebaCFL<mailto:pruebaCFL@noreply.github.com>
CC: jose-tandil-argentina<mailto:josempereztandil@hotmail.com>; Author<mailto:author@noreply.github.com>
Asunto: Re: [jose-tandil-argentina/pruebaCFL] TELEFONO (#5)


@rbeltracchi requested changes on this pull request.


In Camara.ts<https://github.com/jose-tandil-argentina/pruebaCFL/pull/5#discussion_r469498864>:

> @@ -0,0 +1,6 @@

+

+class Camara {

+    public savarFoto(): string{

falta el constructor


In Telefono.ts<https://github.com/jose-tandil-argentina/pruebaCFL/pull/5#discussion_r469499229>:

> -

-

-   public getBateriiaActual(): number{

-       return this.bateriaActual;

-   }

-

-

-}

-

-

-class Camara {

-    public savarFoto(): string{

-        return "la foto del dia";

-    }

-}

+import {Telefono} from "./Telefono1";



 class TelefonoConCamara extends Telefono{

     private camara: Camara;

Camara de donde viene? Tendrias que importar esa clase tambien

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://github.com/jose-tandil-argentina/pruebaCFL/pull/5#pullrequestreview-466220629>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AQDGBEDLJ7COU77OV5XEXMTSALWSHANCNFSM4P3CHGNQ>.

2020-08-26 18:29 UTC, rbeltracchi requested changes
faltan resolver comentarios

2020-08-27 17:51 UTC, rbeltracchi requested changes

2020-08-27 17:51 UTC, rbeltracchi commented on Telefono.ts
> +class Camara extends TelefonoConCamara{
Una camara que extiende de telefono con Camara? Esto no esta bien

2021-07-13 23:08 UTC, closed without merging