Ejercicio2
jose-tandil-argentina/pruebaCFL pull request #7
Opened 2020-08-26 14:27 UTC by jose-tandil-argentina

les dejo el ejercicio!! le faltan cosas de lo cual voy a segir revisando

2020-08-26 14:33 UTC, mauri52 commented on legajosDeColegio.ts
> +    private DarDealtaAlumno:boolean;
los atributos no deberian tener nombre de accion

2020-08-26 14:36 UTC, mauri52 requested changes
Revisa el planteo... o por lo menos los nombres de las clases.
La clase Colegio deberia estar compuesta por la Clase alumnos.
Un colegio suele tener varios alumnos.

2020-08-26 18:00 UTC, jose-tandil-argentina commented
Vos decis  class Alumnos primero y despues La clase Colegio que extienda de alumnos??

Enviado desde Correo<https://go.microsoft.com/fwlink/?LinkId=550986> para Windows 10

De: mauri52<mailto:notifications@github.com>
Enviado: miércoles, 26 de agosto de 2020 11:36
Para: jose-tandil-argentina/pruebaCFL<mailto:pruebaCFL@noreply.github.com>
CC: jose-tandil-argentina<mailto:josempereztandil@hotmail.com>; Author<mailto:author@noreply.github.com>
Asunto: Re: [jose-tandil-argentina/pruebaCFL] Ejercicio2 (#7)


@mauri52 requested changes on this pull request.

Revisa el planteo... o por lo menos los nombres de las clases.
La clase Colegio deberia estar compuesta por la Clase alumnos.
Un colegio suele tener varios alumnos.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://github.com/jose-tandil-argentina/pruebaCFL/pull/7#pullrequestreview-475554940>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AQDGBEG5IQZBNLQRUJ5R643SCUMXTANCNFSM4QL4QZOQ>.

2020-08-27 17:56 UTC, rbeltracchi requested changes
Jose, como ya te corrigio Mauri, hay muchos errores en el planteo de las clases, los nombres de variables y metodos que dicen que hacen una cosa pero hacen otra diferente.

2020-08-27 17:56 UTC, rbeltracchi commented on legajosDeColegio.ts
> +    private DarDealtaAlumnos: string;
Un verbo como un atributo? Eso tiene nombre de metodo

2020-08-27 17:56 UTC, rbeltracchi commented on legajosDeColegio.ts
> +    private Promedio: number;
Los atributos no empiezan con Mayuscula

2020-08-27 17:56 UTC, rbeltracchi commented on legajosDeColegio.ts
> +    public setAdminitrarAlumnos(AdministradorDeAlumnos: string): void{
Yo no veo que agregue a cada alguno, solo setea un string, que funcionalidad tiene administrador de alumnos?

2020-08-27 17:56 UTC, rbeltracchi commented on legajosDeColegio.ts
> +    public setPromedio = (number) =>{
Esto calcula bien el promedio?

2020-08-27 17:56 UTC, rbeltracchi commented on legajosDeColegio.ts
> +            this.AdministradorDeAlumnos+= this.Suma/this.Promedio;
estas usando una variable string para guardar el resultado de una cuenta?

2020-08-27 17:56 UTC, rbeltracchi commented on legajosDeColegio.ts
> +class Alumno extends Colegio{
que tienen en comun un alumno y un colegio para aplicar una herencia?

2020-08-27 17:56 UTC, rbeltracchi commented on legajosDeColegio.ts
> +    public constructor(){
No se deberian crear con su informacion?

2020-09-01 00:39 UTC, rbeltracchi requested changes
Hay solo una clase, cuando tendria que haber mas, como un colegio va a manejar el nombre y apellido del alumno? Cada alumno tendria que tener su propio nombre y apellido, sus notas. Pudiste hacer una prueba en tu maquina del codigo?

2021-07-05 14:11 UTC, closed without merging